name: Deploy ZeroChaos AI Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install express node-fetch dotenv

      - name: Create server file
        run: |
          mkdir server
          cat > server/index.js <<'EOF'
          import express from "express";
          import fetch from "node-fetch";
          import dotenv from "dotenv";
          dotenv.config();

          const app = express();
          app.use(express.json());

          app.post("/ai-sort", async (req, res) => {
            const { tasks } = req.body;
            const response = await fetch("https://api-inference.huggingface.co/models/gpt2", {
              method: "POST",
              headers: {
                "Authorization": `Bearer ${process.env.HF_API_TOKEN}`,
                "Content-Type": "application/json"
              },
              body: JSON.stringify({ inputs: `Order these tasks by difficulty: ${tasks.join(", ")}` })
            });
            const data = await response.json();
            res.json(data);
          });

          const PORT = process.env.PORT || 3000;
          app.listen(PORT, () => console.log("✅ ZeroChaos AI backend running on port", PORT));
          EOF

      - name: Run server (temporary for testing)
        env:
          HF_API_TOKEN: ${{ secrets.HF_API_TOKEN }}
        run: node server/index.js
